test('launch app', async () => {
  throw new Error('Simulated error');
});
